databases:
  - name: white-orion-international-db
    databaseName: white-orion-international-db
    user: white-orion-international-db
    plan: free

services:
  - type: web
    plan: free
    name: white-orion-international-db
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: white-orion-international-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
